#!/usr/bin/env node
/*
  generate-config.js
  Writes config.local.js based on environment variable OPENWEATHER_API_KEY
  Usage (PowerShell):
    $env:OPENWEATHER_API_KEY = 'your_key_here'; node scripts/generate-config.js
  This overwrites `config.local.js` in the project root.
*/
const fs = require('fs');
const path = require('path');

const key = process.env.OPENWEATHER_API_KEY || '';
const outPath = path.resolve(__dirname, '..', 'config.local.js');
const contents = `// Generated by scripts/generate-config.js on ${new Date().toISOString()}\n` +
  "// Set your OpenWeatherMap API key here or leave blank to use public fallbacks.\n" +
  `window.OPENWEATHER_API_KEY = '${key.replace(/'/g, "\\'")}';\n`;

try {
  fs.writeFileSync(outPath, contents, { encoding: 'utf8' });
  console.log('Wrote', outPath);
  if (!key) console.log('No OPENWEATHER_API_KEY set — config written with empty key.');
  else console.log('OPENWEATHER_API_KEY was written to config.local.js');
} catch (err) {
  console.error('Failed to write config.local.js', err);
  process.exitCode = 1;
}
